AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  fast-api

  Sample SAM Template for fast-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  FastAPIApp:
    # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: fastapi-lambda-example
      CodeUri: ./
      Handler: example_app.main.handler
      Runtime: python3.7
      Timeout: 300 # timeout of your lambda function
      MemorySize: 128 # memory size of your lambda function
      Description: fastAPI AWS lambda example
      Events:
        ApiEvent:
          # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Type: Api
          Properties:
            RestApiId:
              Ref: FastAPIGateway
            Path: /{proxy+}
            Method: ANY
      # other options, see ->
      # https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html#sam-specification-template-anatomy-globals-supported-resources-and-properties
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/FastAPILambdaRole

  FastAPIGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      OpenApiVersion: '3.0.0'


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  FastAPI:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev/"
  HelloWorldFunction:
    Description: "FastAPI Lambda Function ARN"
    Value: !GetAtt FastAPIApp.Arn
  FastAPILambdaRole:
    Description: "Implicit IAM Role created for FastAPI function"
    Value: !GetAtt FastAPILambdaRole.Arn
